arm64: hw_breakpoint compile error fixing
When backport commit,
	arm64: kernel: implement HW breakpoints CPU PM notifier
We have the following compile error, that is due to on 3.10, we still
need to use __get_cpu_var instead of this_cpu_ptr. This patch is
to fix it.

arch/arm64/kernel/hw_breakpoint.c: In function ‘hw_breakpoint_reset’:
arch/arm64/kernel/hw_breakpoint.c:864:15: error: cast specifies array type
arch/arm64/kernel/hw_breakpoint.c:873:15: error: cast specifies array type
make[1]: *** [arch/arm64/kernel/hw_breakpoint.o] Error 1

Signed-off-by: Alex Shi <alex.shi@linaro.org>